### ISSUE TITLE
Mismatched dimension

### ISSUE THREAD

**Issue by Nerdyvedi** [zdyshine/RTC2020_EfficientSR#1]
Class IMDModule_So
`out = torch.cat([distilled_c1, distilled_c2, out_c3, input, x_sobel], dim=1)`
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 181 and 180 in dimension 2

Dimensions of tensors in the above operation are:
torch.Size([1, 3, 180, 250]),torch.Size([1, 3, 180, 250]),torch.Size([1, 9, 180, 250]),torch.Size([1, 12, 180, 250]),torch.Size([1, 3, 181, 250]) respectively
The size of x_sobel tensor is 1,3,181,250. That is why I am getting a dimension mismatch.

I am upscaling by scaling factor 2. Low resolution image size is (181,250,3)

Could you please share how to fix this ? Thanks

**Comment by zdyshine** [comment]
I think that the size of the input image cannot be divisible by 2, which results in that it cannot be restored to its original size. You can try to padding the input image to make the size divisible by 2. Also note that the padding part needs to be cut off for the SR result.

**Comment by Nerdyvedi** [comment]
@zdyshine . Got it. Thanks
