### ISSUE TITLE
The downsample scale for the PixelUnshuffle module

### ISSUE THREAD

**Issue by akineeic** [zdyshine/RTC2020_EfficientSR#4]
Thanks for your sharing code. But I have a question about this [line](https://github.com/zdyshine/RTC2020_EfficientSR/blob/master/codes/model/model.py#L252). Should this downscale_factor keep to 2 or keep the same with the scale factor of the SR task?

**Comment by zdyshine** [comment]
There is no limit to the downsampling factor,  you can modify it according to the network inference speed and the image restoration quality.

**Comment by akineeic** [comment]
Got it, thanks for your quick reply!
